### ISSUE TITLE
Bug: can't type after delete Variable used in workspace

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#48] opened 2022-02-20 07:02 UTC
if i try to delete the variable used in workspace. whenever i get this popup, after that i cant able to type in blocks. 
i think same bug which is mentioned in Bug #18. 

![11](https://user-images.githubusercontent.com/86342573/154832216-cd855599-72d0-4581-95fa-d33144651820.png)

**Comment by zhengyangliu** [comment] 2022-02-24 02:13
Duplicate of https://github.com/openblockcc/openblock-desktop/issues/36

**Closed** 2022-02-24 02:14 UTC
