### ISSUE TITLE
Bug: While uploading code, libraries not copied to Projectpath

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#62] opened 2022-03-19 08:31 UTC
If i tried to upload a code with external libraries, Its getting Failed. If i tried to find the Library in project path, Library is not copied.

![Screenshot 2022-03-19 135000](https://user-images.githubusercontent.com/86342573/159113852-12b20294-390d-4d7e-8d3c-2a28775c2804.png)
![Screenshot 2022-03-19 135111](https://user-images.githubusercontent.com/86342573/159113907-0ee00ac3-affd-4d57-ad7a-080b1e4e41d0.png)

**Comment by ircbloqcc** [comment] 2022-04-01 11:31
any update regarding this issue??

**Comment by zhengyangliu** [comment] 2022-04-03 15:01
WTF? I will check what happen.

**Comment by zhengyangliu** [comment] 2022-04-03 15:23
I found it. Since the new version of openblock desktop has adjusted the naming and added a space in the middle, the cache path contains space characters, which makes the arduino cli parsing error. I will fix this soon.

**Comment by zhengyangliu** [comment] 2022-04-03 15:24
![image](https://user-images.githubusercontent.com/10896145/161435130-7f0d2154-3018-46df-aac1-4bda74a8a824.png)

**Comment by zhengyangliu** [comment] 2022-04-03 15:28
In v2.2.9 this problem should exist

**Comment by zhengyangliu** [comment] 2022-04-04 01:51
My mistake, not the cause of the problem.. This is because in the v2.3.0 version, a cli tool will be used to optimize the external resource when it is released, and useless files will be deleted to reduce the library size. But I deleted the library.properties file by mistake, which caused the arduino cli to not recognize the library correctly and cause this error. Just update external-reource and i will fix this soon.

**Comment by zhengyangliu** [comment] 2022-04-04 04:59
Fixed in https://github.com/openblockcc/openblock-resource-cli/commit/16bb06d1c931563657af123b15472fa3ea06d753.
The software will automatically detect external-resource v0.0.4 and update it to fix.

**Closed by zhengyangliu** 2022-04-04 04:59 UTC
