### ISSUE TITLE
Heap memory error in make exe openblock-desktop

### ISSUE THREAD

**Issue by jaimin1234568** [openblockcc/openblock-desktop#73] opened 2024-07-09 07:08 UTC
my system in node version 14.16.0. and npm version 6.4.1 in edit in this repo edit in node_modules/openblock -gui is modified and try build this repo in heap memory issue not make exe openblock-gui -desktop

**Comment by jaimin1234568** [comment] 2024-07-10 10:06
![javascript heap memory](https://github.com/openblockcc/openblock-desktop/assets/140792449/6c65e367-a26d-49c7-ae29-f87a139c6793)

**Comment by zhengyangliu** [comment] 2024-07-10 13:13
Duplicate of https://github.com/openblockcc/openblock-desktop/issues/29

**Closed by zhengyangliu** 2024-07-10 13:13 UTC

**Comment by jaimin1234568** [comment] 2024-07-11 09:46
sir tried this solution and works but my repo does not run the npm run dist build command and does not make exe for my repository
sir my repository size is around 14 GB in store in my system
my system uses window 11, node version 14.16.1, and npm version 6.14.12 and the RAM is 8 GB in my system

**Comment by jaimin1234568** [comment] 2024-07-11 09:50
![heap memory error](https://github.com/openblockcc/openblock-desktop/assets/140792449/a443aea2-3574-4aa9-b5c7-64a7028666e5)

**Comment by zhengyangliu** [comment] 2024-07-11 09:56
`npm run build:dist` not `npm run dist build`. Just check the https://github.com/openblockcc/openblock-desktop/blob/59b2948696386870c6afc32129ccc0d5f11252b7/package.json#L8-L31 These are the available commands.

**Comment by jaimin1234568** [comment] 2024-07-12 06:49
try ths scrpt but error heap memory

**Comment by jaimin1234568** [comment] 2024-07-12 06:49
try this script and package.json file
