### ISSUE TITLE
Bug: adding comments to Device extensions

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#15] opened 2021-08-02 03:14 UTC
After i add comment for device extension block. If i try to load the project, there is another comment window appear which cannot able to delete also.

![Screenshot (34)](https://user-images.githubusercontent.com/86342573/127799729-82137aa7-58c6-469c-a1e2-3b202aba950f.png)

**Comment by zhengyangliu** [comment] 2021-08-02 04:19
Can you upload your project file? I can't reproduce this bug.

**Comment by ircbloqcc** [comment] 2021-08-02 04:32
If i select device and add extension, then Its not coming.

Project file:
[OpenBlock Project.zip](https://github.com/openblockcc/openblock-desktop/files/6914385/OpenBlock.Project.zip)

![op_t](https://user-images.githubusercontent.com/86342573/127804552-cb8130ee-8ebb-4304-b5a8-5df4024b8e00.gif)

![op_ts](https://user-images.githubusercontent.com/86342573/127804569-a863242a-0f7e-415b-bb6d-77e1ecf79638.gif)

**Comment by ircbloqcc** [comment] 2021-08-02 04:43
https://user-images.githubusercontent.com/86342573/127805214-83999a2e-dbc8-4a65-98da-62735d071675.mp4


https://user-images.githubusercontent.com/86342573/127805237-9dead7e0-fc15-4886-bcb0-fbb6190a7fa2.mp4

**Comment by ircbloqcc** [comment] 2021-08-02 04:51
![op11](https://user-images.githubusercontent.com/86342573/127805799-b587c5ba-4c01-4a4e-8400-d6f1acc9fffc.gif)

![op12](https://user-images.githubusercontent.com/86342573/127805834-3e371279-0775-413a-a292-30005cbd0d93.gif)

**Comment by ircbloqcc** [comment] 2021-08-02 05:00
https://user-images.githubusercontent.com/86342573/127806458-194020cb-e281-42cc-8930-8b8e9a5c7fdd.mp4

https://user-images.githubusercontent.com/86342573/127806491-b0a3d663-605a-4024-8c55-4159aec6afc5.mp4

**Comment by ircbloqcc** [comment] 2021-08-02 05:18
![ezgif-6-101684a5b768.gif](https://user-images.githubusercontent.com/86342573/127807704-0cb598fe-19c5-4a0d-9092-fea28d869cf9.gif)

![ezgif-6-b69f3f05f246.gif](https://user-images.githubusercontent.com/86342573/127807724-62d9da42-fe19-4b60-95e0-6d86130ff13b.gif)

**Comment by ircbloqcc** [comment] 2021-08-02 05:22
![Op1](https://drive.google.com/file/d/1JMSCPTpMO6xnSlLiEsN4ogh1IZXozXKL/view?usp=drivesdk)

![op2](https://drive.google.com/file/d/1JS28Y-zpLDe6xVhyhxWgU79YLcUfKOtr/view?usp=drivesdk)

**Comment by ircbloqcc** [comment] 2021-08-02 05:26
![op1](https://user-images.githubusercontent.com/86342573/127808286-6f64f215-1182-4cfd-be6e-8a04af2537c3.gif)

![Uploading ezgif-6-b69f3f05f246.gif…]()

**Comment by zhengyangliu** [comment] 2021-08-02 11:13
This bug has been fixed in https://github.com/openblockcc/openblock-vm/commit/46d8caaa181037a5e5cdd18d6f928586cdfe80e4

**Comment by zhengyangliu** [comment] 2021-08-02 11:15
> This bug has been fixed in [openblockcc/openblock-vm@46d8caa](https://github.com/openblockcc/openblock-vm/commit/46d8caaa181037a5e5cdd18d6f928586cdfe80e4)

The repaired code will be used in the v2.2.3 packaging. I will close this issue if the test is no problem.

**Comment by ircbloqcc** [comment] 2021-08-02 17:55
Tested.. Its Working..
Thank you..

**Comment by zhengyangliu** [comment] 2021-08-03 01:49
fix in https://github.com/openblockcc/openblock-desktop/tree/v2.2.3

**Closed by zhengyangliu** 2021-08-03 01:49 UTC
Labels: bug
