### ISSUE TITLE
Bug: Project is not Loading when i double click from saved location

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#14] opened 2021-07-28 13:38 UTC
Still the issues there in Version 2.2.2.
If i opened the Saved project from location where i saved by Double click. OpenBlock App is opening But Project is not Loading. It shows EMPTY.
![Screenshot (32)](https://user-images.githubusercontent.com/86342573/127331809-98e0d5e4-5a18-41ea-a9ed-23098bc73159.png)

_Originally posted by @ircbloqcc in https://github.com/openblockcc/openblock-desktop/issues/8#issuecomment-888316053_

**Comment by zhengyangliu** [comment] 2021-07-28 13:55
Pelese upload your project file. I need it to check the bug.

**Comment by ircbloqcc** [comment] 2021-07-28 14:06
If i Load from the APP, it is loading. But it is not Loading when i double click the Project file directly from saved Location.
This is the project file.
[OpenBlock Project.zip](https://github.com/openblockcc/openblock-desktop/files/6893713/OpenBlock.Project.zip)

this is the screenshot that i load from application.

![Screenshot (33)](https://user-images.githubusercontent.com/86342573/127336203-a2a32237-f4fa-4b02-b4ce-ca4fa5784914.png)

**Comment by ircbloqcc** [comment] 2021-07-28 14:16
![op1](https://user-images.githubusercontent.com/86342573/127338031-39e5f120-233c-42b0-b0e6-915d05c83956.gif)

![op2](https://user-images.githubusercontent.com/86342573/127338042-6e630a3a-7ed8-4525-8212-5d38b8f3cb35.gif)

**Comment by zhengyangliu** [comment] 2021-07-28 16:45
Indeed, the bug still exists, but I don't know what's wrong. It is expected to take a lot of time to fix it. At present, it is only recommended not to use this function.

**Comment by ircbloqcc** [comment] 2021-07-28 16:49
Yeah.. thank you.. 
But this bug is not there in V2.1.1

**Comment by zhengyangliu** [comment] 2021-07-28 16:50
This bug should be caused by some interfaces not updated after merging the official content of LLK in v2.2.x

**Comment by ircbloqcc** [comment] 2021-07-28 16:56
I think the problem is loading with device id. 
Without selecting device. if i saved the project, it is opening the project without error.

**Comment by ircbloqcc** [comment] 2021-07-31 14:54
Found the bug. It is in openblock-vm. due to this [clearMonitor function]( https://github.com/openblockcc/openblock-vm/commit/e8d518c5d7244e40c8220e87f6f3a4e7fcb084b3#diff-9362558266dae3ef23277f5983150d157e3e325843cdb30ce0b0b64106337574)

**Comment by zhengyangliu** [comment] 2021-07-31 15:45
Ah ha. This seems very likely to be the cause of the problem. Have you verified this conclusion? It's too late today. I'll test it tomorrow. If so, I'll find a way to fix it

**Comment by ircbloqcc** [comment] 2021-07-31 15:56
Yeah I have tested by commenting that option. Its worked.

**Comment by zhengyangliu** [comment] 2021-08-02 11:12
This bug has been fixed in https://github.com/openblockcc/openblock-vm/commit/8f76a3e8fe72689d8cfd7e57ecfaa6c4511f9188.

**Comment by zhengyangliu** [comment] 2021-08-02 11:15
> This bug has been fixed in [openblockcc/openblock-vm@8f76a3e](https://github.com/openblockcc/openblock-vm/commit/8f76a3e8fe72689d8cfd7e57ecfaa6c4511f9188).

The repaired code will be used in the v2.2.3 packaging. I will close this issue if the test is no problem.

**Comment by ircbloqcc** [comment] 2021-08-02 17:55
Tested.. Its Working..
Thank you..

**Comment by zhengyangliu** [comment] 2021-08-03 01:50
fixed in https://github.com/openblockcc/openblock-desktop/tree/v2.2.3

**Closed by zhengyangliu** 2021-08-03 01:50 UTC
Labels: bug
