### ISSUE TITLE
Mac Build version 2.2.9

### ISSUE THREAD

**Issue by CeemaCR** [openblockcc/openblock-desktop#50] opened 2022-03-01 13:43 UTC
With version, V 2.2.8 the source code for Mac, took a build. 

1. First external resource files were not available.
2. Copied it from old versions, which we were using earlier.  
3. Then, Arduino Nano /Uno is showing an upload error - timeout

Any advice, please
![Mac Upload](https://user-images.githubusercontent.com/82566442/156179343-8bccbac5-238e-4047-a4c3-d86a4b542f62.JPG)

![issue2](https://user-images.githubusercontent.com/82566442/156305349-beb994c7-1772-4e5e-bc43-ea6a3fff8f11.JPG)

**Comment by zhengyangliu** [comment] 2022-03-02 11:28
I will find and fix this soon.

**Comment by zhengyangliu** [comment] 2022-03-02 11:29
Duplicate of #31

**Comment by zhengyangliu** [comment] 2022-03-02 12:39
It's a strange problem, I will do a test on the mac system.

**Comment by zhengyangliu** [comment] 2022-03-06 06:02
I am sure that this problem is no longer in the v2.3.0 version.

**Closed by zhengyangliu** 2022-03-06 06:02 UTC
