### ISSUE TITLE
Bug: After loading the saved project, i cannot able to edit the text. 

### ISSUE THREAD

**Issue by ircbloqcc** [openblockcc/openblock-desktop#18] opened 2021-08-17 12:39 UTC
If i try to edit the loaded project in openblock, i cannot able to edit text. Even after try to open a NEW project also having same problem

![Screenshot (36)](https://user-images.githubusercontent.com/86342573/129726826-ccb1d908-ea5e-4511-9eb9-abedcf7acd6e.png)

Actually text selection should show blue color. But it shows in gray color. Keyboard are not working. If i save the loaded project again, then only it can able to edit the text.

**Comment by ircbloqcc** [comment] 2021-08-17 13:20
![op123](https://user-images.githubusercontent.com/86342573/129733004-a9ff55a3-dc5b-4b0c-b63e-b8a2a2517295.gif)

**Comment by zhengyangliu** [comment] 2021-08-28 05:34
I also found this bug and am looking for what went wrong。

**Comment by zhengyangliu** [comment] 2021-08-28 05:41
I don't know which commit fixed the bug. But this bug no longer exists. I think it may be caused by the infinite reentry of the startheartbeat function in the previous code.  https://github.com/openblockcc/openblock-vm/commit/63aeb45597d520eeda398c3cc6c94c26282e5454

**Comment by zhengyangliu** [comment] 2021-08-28 05:42
This bug will be fixed in v2.2.5

**Comment by ircbloqcc** [comment] 2021-08-28 06:23
Thank you

**Comment by zhengyangliu** [comment] 2021-08-28 10:28
The bug sitll exists.

**Comment by ircbloqcc** [comment] 2021-08-28 10:31
:( But this problem also there in Official Scratch desktop application.

**Comment by zhengyangliu** [comment] 2021-08-28 11:18
WTF. I found the operation to remove the error: move the focus out of the electron and come back. But I don't know how to fix this bug。

**Comment by zhengyangliu** [comment] 2021-08-28 11:37
This is a bug from electron. https://github.com/electron/electron/issues/19977. We need to replace all alert and comfim to fix this problem.

**Comment by zhengyangliu** [comment] 2021-08-29 11:07
After i replace all alert and comfim to electron dialog. This bug has been fixed.

**Closed by zhengyangliu** 2021-08-29 11:07 UTC
Labels: bug
